name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
      
      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Run script
        env: 
          IS_TEST: ${{ vars.IS_TEST }}
          API_KEY: ${{ secrets.API_KEY }}
        run: uv run main.py